export const OBJECTIVE_TITLES: Record<string, string> = {
  E1: "Learning objectives are specific, measurable, and clearly defined.",
  E2: "Course lists all required learning materials, including technology tools.",
  E3: "Course provides office hours, communication preferences, and response times.",
  E4: "Course provides technical support resources and help for common technical issues.",
  E5: "Course includes step-by-step guides or tutorials for all required technologies.",
  E6: "Course defines grading policies, academic integrity expectations, and late policies.",
  E7: "Course provides an accessibility statement and steps to request accommodations.",
  E8: "Course includes information for relevant learner support and other services.",
  E9: "Course includes a course schedule with due dates for all assignments and activities.",
  E10: "Course includes an introductory discussion and guidelines for student interactions.",
  E11: "Course site navigation and layout are clear and consistent.",
  E12: "Videos and other multimedia content are of appropriate quality and length.",
  E13: "Course content is up-to-date, relevant, and tied to specific learning objectives.",
  E14: "Course site provides an organized gradebook that includes all assessments.",
  E15: "Course incorporates formative, low-stakes assessments for frequent engagement.",
  E16: "Course provides a scaffolded approach for summative assessments.",
  E17: "All modules, assignments, and activities include clear and detailed instructions.",
  E18: "Course includes rubrics for all assignments and assessments.",
  E19: "Course workload is balanced and appropriate for the discipline and course level.",
  E20: "Course materials are free of broken links, spelling errors, and incorrect information.",
  A1: "Course learning objectives and/or outcomes use learner-centered language.",
  A2: "Course includes a pre-course technology checklist and online readiness quiz.",
  A3: "Course includes an orientation module, video, or guide to navigating the course.",
  A4: "Course includes explicit guidelines for using generative AI.",
  A5: "Course uses exclusively low- or no-cost materials.",
  A6: "Course provides multiple pathways for learners to meet learning objectives.",
  A7: "Content includes examples that represent a range of learner backgrounds.",
  A8: "Course includes an online forum for muddiest points or questions about the course.",
  A9: "Course incorporates adaptive learning strategies to personalize learning.",
  A10: "Text materials meet accessibility and Universal Design standards.",
  A11: "Videos and other multimedia content meet accessibility standards.",
  A12: "Course includes ways for learners to contribute meaningfully to course content.",
  A13: "Course includes model deliverables for summative assessments.",
  A14: "Course includes assessments with practical, real-world applications.",
  A15: "Course supports learner metacognition through periodic self-reflection activities.",
  D1: "Instructor provides a personal introduction to the course.",
  D2: "Instructor releases modules and content in the course site in a timely manner.",
  D3: "Instructor posts regular and relevant announcements on the course site.",
  D4: "Instructor contributes meaningfully to online activities and discussions.",
  D5: "Instructor provides specific and targeted feedback on assignments.",
  D6: "Instructor provides feedback and grades on assessments in a timely manner.",
  D7: "Instructor actively engages with learners who show signs of struggle in the course.",
  D8: "Instructor uses supportive language in all feedback and communications.",
  D9: "Instructor encourages or incentivizes learners to participate in office hours.",
  D10: "Instructor responds to student communications and inquiries in a timely manner.",
  D11: "Instructor provides end-of-module summaries based upon learner contributions.",
  D12: "Instructor encourages learner-to-learner engagement in online activities.",
  D13: "Instructor adjusts content, assignments, and dates in response to learner needs.",
  D14: "Instructor solicits learner feedback about the course at multiple points in the term.",
  D15: "Instructor incorporates personal examples to supplement course content.",
}
